from enum import Enum


class ConstraintEvents(Enum):
    CONSTRAINT_STARTED = 0
    CONSTRAINT_ERROR = 1
    CONSTRAINT_INPUT_PASSED = 2
    CONSTRAINT_COMPLETED = 3
    CONSTRAINT_OUTPUT_GENERATED = 4
